insert into reconcileddatalayer.dbo.package
select
	p.PACCD_ID,
	p.paccd_pacc_id,
	p.paccd_soluzione,
	p.paccd_soggiorno,
	p.paccd_data,
	p.paccd_gg,
	p.paccd_notti,
	p.paccd_pax,
	p.paccd_localita,
	p.paccd_hotel_id,
	case when p.paccd_sist_id = 1 then 'Dp RO' else 'SG' end,
	p.paccd_voloa_id,
	p.paccd_volor_id,
	p.paccd_descr,
	p.paccd_note,
	p.paccd_quotas,
	p.paccd_quotan,
	p.paccd_costoe,
	p.paccd_venditae,
	p.paccd_valuta,
	p.paccd_venditav,
	p.paccd_costov,
	p.paccd_quoteextra,
	p.paccd_adlc3,
	p.paccd_adl3,
	p.paccd_chdc3,
	p.paccd_chd3,
	p.paccd_adlc4,
	p.paccd_adl4,
	p.paccd_chdc4,
	p.paccd_chd4,
	p.paccd_ssgc,
	p.paccd_ssg,
	p.paccd_provv,
	p.paccd_mkup
from meridiano.dbo.pacchettid as p