INSERT INTO RECONCILEDDATALAYER.DBO.TICKETS 
SELECT 
    CAST(CONCAT('C-',T.TKT_ID) AS NVARCHAR(50)),
    CAST(T.TKT_NTKT AS NVARCHAR(15)),
    CAST(CONCAT('C-',T.TKT_CLI) AS NVARCHAR(10)),
    CAST(T.TKT_NOMECLI AS NVARCHAR(100)),
    T.TKT_IMPLORDO,
    T.TKT_PROVVIGIONE,
    CAST(T.TKT_NOTE AS NVARCHAR(25)),
    CAST(T.TKT_CIT1D AS NVARCHAR(50)),
    CAST(T.TKT_CIT2D AS NVARCHAR(50)),
    T.TKT_DATACREAZIONE,
     CAST(CONCAT('C-',T.TKT_CODOPERATORE) AS NVARCHAR(15)),
     'ContiTravel'
FROM CONTITRAVEL.DBO.TKT AS T
INNER JOIN RECONCILEDDATALAYER.DBO.STATIONS AS S
    ON T.TKT_CIT1D = S.NAME
WHERE NOT EXISTS (
    SELECT 1 
    FROM CONTITRAVEL.DBO.VETTORI AS V 
    WHERE V.VETTORI_COD = T.TKT_VETTORE
)
AND T.TKT_CODHOTEL = '';